---
label: Theme configuration
hide_body: true
fields:
- type: text
  name: LDTI
  label: LDTI
- type: textarea
  name: conception__creation_des_dossiers_techniques__conseil_et_expertise_en_amelioration_continue
  label: conception, creation des dossiers techniques, conseil et expertise en amelioration
    continue
- type: textarea
  name: hero_title
  label: Hero title
  config:
    wysiwyg: true
    schema:
      format: html
- type: textarea
  name: hero_subtitle
  label: Hero subtitle
  config:
    wysiwyg: true
    schema:
      format: html
- name: footer
  label: Footer text
  type: text
  hidden: false
  default: ''
- type: boolean
  name: dark_mode
  label: Dark mode
pages:
- data/theme.json
